$(document).ready(function(){
  $(".owl-carousel").owlCarousel({
    autoplay:true,
    autoplayTimeout:3000,
    autoplayHoverPause:true,
    loop:true,
    margin:15,
    responsiveClass:true,
    responsive:{
      0:{
          items:3,
          nav:true
      },
      620:{
            items:4,
            nav:true
      },
      1000:{
             items:5,
             nav:true
      }
    }
  });
});
 